[game]
hostname = "Server Name"
desc = "Server Description"
maxplayers = 64
soft_max_players = 48
type = 1
lobbyenabled = false
lobbyduration = 180
role_timers = false
fallbackpreset = "extended"

[whitelist]
min_players = 32

[rules]
rules.time = 60


[mapping]
autosave_interval = 180.0

[ic]
flavor_text = true

[ooc]
enable_during_round = true

[vote]
map_enabled = true
restart_enabled = true
restart_required_ratio = 0.75
restart_not_allowed_when_admin_online = true
timermap = 45


[console]
loginlocal = true

[hub]
advertise = false

[auth]
# 0 = Optional, 1 = Required, 2 = Disabled
mode = 1
allowlocal = true

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
pvs = true

[status]
enabled = true


[netres]
limit = 0.0


[database]
# Database type to use. Can be "sqlite" or "postgres" currently.
engine = "sqlite"

# Path to store the database at when using SQLite. Note that is NOT a disk path.
# This is relative to the server data directory, which is specified by --data-dir when starting the server from the command (or automatically set by SS14.Watchdog)
sqlite_dbpath = "preferences.db"

# PostgreSQL database configuration, should be self explanatory.
# pg_host = "localhost"
# pg_port = 5432
# pg_database = "ss14"
# pg_username = "ss14"
# pg_password = "ss14"
